apiVersion: tutorial.my.domain/v1
kind: Email
metadata:
  name: test-email
  namespace: default
spec:
  senderConfigRef: mailersend-config
  recipientEmail: mahi@mailinator.com
  subject: Test Email
  body: This is a test email sent from the Kubernetes operator.
