# permissions for end users to view emails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: email-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mailersend
    app.kubernetes.io/part-of: mailersend
    app.kubernetes.io/managed-by: kustomize
  name: email-viewer-role
rules:
- apiGroups:
  - tutorial.my.domain
  resources:
  - emails
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorial.my.domain
  resources:
  - emails/status
  verbs:
  - get
